"""add gdpr_request model & minor changes to other models

Revision ID: 390fd0a1edec
Revises: 4ae04b5a5b77
Create Date: 2025-11-08 00:45:25.931783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '390fd0a1edec'
down_revision: Union[str, Sequence[str], None] = '4ae04b5a5b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define enum values explicitly
transaction_type_enum = postgresql.ENUM(
    'WALLET_DEPOSIT', 'WALLET_WITHDRAWAL',
    'GROUP_SAVINGS_DEPOSIT', 'GROUP_SAVINGS_WITHDRAWAL',
    'INDIVIDUAL_SAVINGS_DEPOSIT', 'INDIVIDUAL_SAVINGS_WITHDRAWAL',
    name='transaction_type_enum'
)
transaction_status_enum = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='transaction_status_enum')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enums first
    transaction_type_enum.create(op.get_bind(), checkfirst=True)
    transaction_status_enum.create(op.get_bind(), checkfirst=True)
    # Alter the transaction table
    op.execute("""
               ALTER TABLE transaction
               ALTER
               COLUMN type
        TYPE transaction_type_enum
        USING type::text::transaction_type_enum
               """)

    op.execute("""
               ALTER TABLE transaction
               ALTER
               COLUMN status
        TYPE transaction_status_enum
        USING status::text::transaction_status_enum
               """)

    op.create_table('gdpr_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_full_name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_type', sa.Enum('DATA_EXPORT', 'DATA_MODIFICATION', name='gdpr_request_type_enum'), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'REFUSED', name='gdpr_request_status_enum'), server_default='PROCESSING', nullable=False),
    sa.Column('refusal_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transaction_status_enum'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='transactionstatus'),
               existing_nullable=False)
    op.alter_column('transaction', 'type',
               existing_type=sa.Enum('WALLET_DEPOSIT', 'WALLET_WITHDRAWAL', 'GROUP_SAVINGS_DEPOSIT', 'GROUP_SAVINGS_WITHDRAWAL', 'INDIVIDUAL_SAVINGS_DEPOSIT', 'INDIVIDUAL_SAVINGS_WITHDRAWAL', name='transaction_type_enum'),
               type_=postgresql.ENUM('WALLET_DEPOSIT', 'WALLET_WITHDRAWAL', 'GROUP_SAVINGS_DEPOSIT', 'GROUP_SAVINGS_WITHDRAWAL', 'INDIVIDUAL_SAVINGS_DEPOSIT', 'INDIVIDUAL_SAVINGS_WITHDRAWAL', name='transactiontype'),
               existing_nullable=False)
    op.drop_table('gdpr_request')
    # ### end Alembic commands ###
