"""add total_balance, locked_amount fields to wallet model & transient available_balance

Revision ID: 4ac3768cf6be
Revises: 390fd0a1edec
Create Date: 2025-11-08 14:02:49.190285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac3768cf6be'
down_revision: Union[str, Sequence[str], None] = '390fd0a1edec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('total_balance', sa.Numeric(precision=15, scale=4), nullable=False))
    op.add_column('wallet', sa.Column('locked_amount', sa.Numeric(precision=15, scale=4), nullable=False))
    op.drop_column('wallet', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('balance', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=False))
    op.drop_column('wallet', 'locked_amount')
    op.drop_column('wallet', 'total_balance')
    # ### end Alembic commands ###
