"""update - make timestamp fields in wallet & transaction models to be timezone aware & set default values for wallet total_balance, locked_amount

Revision ID: 66839dff44ee
Revises: 4ac3768cf6be
Create Date: 2025-11-08 14:48:21.478134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66839dff44ee'
down_revision: Union[str, Sequence[str], None] = '4ac3768cf6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('wallet', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)

    # Manually add defaults to wallet columns
    op.alter_column('wallet', 'total_balance',
                    server_default=sa.text('0'),
                    existing_type=sa.Numeric(15, 4),
                    existing_nullable=False)
    op.alter_column('wallet', 'locked_amount',
                    server_default=sa.text('0'),
                    existing_type=sa.Numeric(15, 4),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('transaction', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)

    # Remove defaults on wallet columns
    op.alter_column('wallet', 'total_balance',
                    server_default=None,
                    existing_type=sa.Numeric(15, 4),
                    existing_nullable=False)
    op.alter_column('wallet', 'locked_amount',
                    server_default=None,
                    existing_type=sa.Numeric(15, 4),
                    existing_nullable=False)
    # ### end Alembic commands ###
