"""update - add is_anonymized field to User for GDPR anonymization and update relationships for soft delete compliance

Revision ID: 9ec7c28e67dc
Revises: 66839dff44ee
Create Date: 2025-11-08 20:02:22.543105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec7c28e67dc'
down_revision: Union[str, Sequence[str], None] = '66839dff44ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE role_enum ADD VALUE 'DELETED_USER';")

    op.add_column('app_user', sa.Column('is_anonymized', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('exchange_rate', sa.Column('is_anonymized', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('transaction', sa.Column('is_anonymized', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('transaction', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('wallet', sa.Column('is_anonymized', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('wallet', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('wallet', 'is_anonymized')
    op.alter_column('transaction', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('transaction', 'is_anonymized')
    op.drop_column('exchange_rate', 'is_anonymized')
    op.drop_column('app_user', 'is_anonymized')
    # ### end Alembic commands ###
