"""update - add stag to user model

Revision ID: fc3cd89f494b
Revises: 2fa8d3ee3f10
Create Date: 2025-11-28 05:31:34.848205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fc3cd89f494b'
down_revision: Union[str, Sequence[str], None] = '2fa8d3ee3f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('stag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_app_user_stag'), 'app_user', ['stag'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_stag'), table_name='app_user')
    op.drop_column('app_user', 'stag')
    # ### end Alembic commands ###
